# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Pavel Karateev
tagline:             R, Data Science, Visualization
description:         'A personal blog about R, Data Science and Visualization'
url:                 http://pavelkarateev.com
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Pavel Karateev
  url:               https://twitter.com/Lancel0te
  email:             karateev.pavel@ya.ru

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/lancelote/lancelote.github.io

exclude:             [Rmarkdown]

profiles_list:
  GitHub:  'http://github.com/lancelote'
  Google+: 'https://plus.google.com/+PavelKarateev'
  Twitter: 'https://twitter.com/Lancel0te'
  VK:      'https://vk.com/lancelote'
